### ISSUE TITLE
Excepción en agente 3.0.0

### ISSUE THREAD

**Issue by fernando-reyes** [TransbankDevelopers/transbank-pos-sdk-web-agent#12]
Estimados 

Probando el agente 3.0.0 en conjunto con la aplicación de https://pos.digitalpartner.cl, en un kit de pruebas, el agente muestra este mensaje.
![imagen](https://user-images.githubusercontent.com/35506065/119890745-341da880-bf06-11eb-8606-37616027c29f.png)

Volví a instalar la versión 2.1.0 y funciona correctamente.

Será que ya no hay soporte para Window$ 7 64 bits ?

Lo otro, en este mismo S.O. al minimzar el agente se mueve correctamente a la traybar, no obstante no muestra ícono.

Gracias.

**Comment by mastudillot** [comment]
Estamos liberando una nueva versión del agente, al igual que que la versión 3.0.0 debe funcionar con el SDK web 3.0.0, el proyecto de ejemplo de la web https://pos.digitalpartner.cl no se encuentra actualizado con el SDK web 3.0.0, lo mas probable es que por eso se este presentando el error. Estamos en proceso de actualizar el proyecto de ejemplo.

**Comment by gdespirito** [comment]
@fernando-reyes agradecemos nos puedas confirmar si esta nueva versión soluciona el problema :)

**Comment by fernando-reyes** [comment]
> 
> 
> @fernando-reyes agradecemos nos puedas confirmar si esta nueva versión soluciona el problema :)

Todo ok ahora gracias.

**Comment by mastudillot** [comment]
En la siguiente versión del agente quedara solucionado el problema con el traybar 👍
