### ISSUE TITLE
Problema Version 3.1.1

### ISSUE THREAD

**Issue by vaguilarrebolledo** [TransbankDevelopers/transbank-pos-sdk-web-agent#18]
al minimizar no existe icono del agente

![imagen](https://user-images.githubusercontent.com/7340407/124793078-a331e800-df1b-11eb-98ce-d4e97ffa605e.png)

**Comment by gdespirito** [comment]
Pensamos que esto estaba resuelto en la última versión. cc @DarkFrostnight

**Comment by gdespirito** [comment]
Gracias por reportarlo @vaguilarrebolledo .

**Comment by mastudillot** [comment]
El último PR lo soluciona pero no he sacado release por si podía sumar algo más, voy a sacar versión con el arreglo.
@gonzunigad. Muchas gracias por el reporte.

**Comment by mastudillot** [comment]
Se genero nueva versión que soluciona el problema. Se puede descargar desde aquí https://github.com/TransbankDevelopers/transbank-pos-sdk-web-agent/releases/tag/3.1.2
