### ISSUE TITLE
Error al minimizar

### ISSUE THREAD

**Issue by fernando-reyes** [TransbankDevelopers/transbank-pos-sdk-web-agent#8]
Estimados

Al minimizar el agente se muestra este mensaje...
![imagen](https://user-images.githubusercontent.com/35506065/113322775-7f8f4e00-92eb-11eb-86ac-96441049c8c9.png)

Cambié el "src/assets/tbk.png" por el "src/assets/icons/icon.ico", compilé y se fué el error...
src/index.ts(110)
//let appIcon = new Tray(path.join(__dirname, '../../src/assets/icons/icon.ico'));
let appIcon = new Tray(path.join(__dirname, '../../src/assets/tbk.png'));

window$ 7 pro sp1 64.
node 12.18.1

**Comment by gdespirito** [comment]
Hola @fernando-reyes . Gracias por el reporte. 
Esta funcionalidad de minimizar al tray se añadió hace muy poco. 

Mi primera duda es ¿poruqe montas el agente desde el repositorio? ¿Estás haciendo cambios para adaptarlo a tu negocio?
Es solo para confirmar si sabes que hay un .exe descargable con la versión estable disponible :)

Sobre este error, no sé muy bien porque podría pasar. En la documentación @cfficaurzua me indica que se solicita un png. ¿Tu lo cambias a ico y te funciona?

**Comment by fernando-reyes** [comment]
Hola Gonzalo

Sorry olvidé mencionar que corresponde al último commit.

Avisaron por slack de una actualización y al revisar el agente web lo ví actualizado, lo descargué del repo y probé.

Dicha funcionalidad (tray) ya la había implementado yo en mi pc y por eso ya me había encontrado con este problema, pero prefiero mantener el código lo mas intacto posible, por lo que no te preocupes ya que sólo hice esto para aportar mis 2 centavos, en producción sigo ocupando el instalador oficial (https://github.com/TransbankDevelopers/transbank-pos-sdk-web-agent/releases).

Efectivamente el constructor del Tray recibe un parámetro con la ruta de la imagen o un objeto que la contenga, pero ignoro si el formato "debe" ser ico, lo que sí veo es que la documentación recomienda que para el caso de windows$ sí sea un ICO.
Referencia: https://www.electronjs.org/docs/api/tray
![imagen](https://user-images.githubusercontent.com/35506065/113339281-a441f080-9300-11eb-8cea-5f5cb824c801.png)

Acabo de ver el post de Cristóbal y creo que lo implementó en window$ 10, ta vez sea problema con 7.

**Comment by gdespirito** [comment]
Excelente. Gracias por la irno y gracias por meterte s aportsr. Que bueno que me mandaste el link a la doc. Creo wue toca hacer el cambio a .ico, al menos en windows 7. Intentaré revisarlo, pero si quieres, podrias hacer un Pull Request con el cambio :)

**Comment by vaguilarrebolledo** [comment]
Hola, a mi me aparece exactamente lo mismo, se corrige el problema con lo mencionado en desarrollo, pero al crear el .exe igual sigue arrojando el error

**Comment by mastudillot** [comment]
La versión 3.1.1 del agente solucionará el problema del traybar y el ícono.
